#!/usr/bin/env python3
"""Emit a compose override with N member services on scattered addresses,
and (with --targets) the Prometheus file_sd target list for those members.

The registrar's anti-sybil term scores how many address-prefix bits an
advertiser shares with the ads it already holds (nim-libp2p iptree.ipScore),
and every shared bit costs advertExpiry/32 of waiting. Sequential container
addresses in one /24 share ~27 bits -> 13-15 min per registration. Spreading
the members over the whole subnet leaves only the subnet prefix shared.

The first 256 addresses of the subnet are reserved for the fixed
infrastructure (seed, prometheus, grafana).

Usage: gen-members.py <count> [subnet] [--targets <file.json>] > out/members.yml
"""
import ipaddress, json, sys

argv = [a for a in sys.argv[1:]]
targets_file = None
if "--targets" in argv:
    i = argv.index("--targets")
    targets_file = argv[i + 1]
    del argv[i : i + 2]

count = int(argv[0])
net = ipaddress.ip_network(argv[1] if len(argv) > 1 else "10.0.0.0/8")
seed = net[10]
METRICS_PORT = 9100
SEED_METRICS_PORT = 8008
INFRA = 256  # seed .10, prometheus .11, grafana .12 live here
span = net.num_addresses - INFRA - 2
used = {seed}
services = []
for i in range(1, count + 1):
    h = (i * 2654435761) & 0xFFFFFFFF
    ip = net[INFRA + h % span]
    while ip in used:
        ip += 1
    used.add(ip)
    services.append((f"m{i}", ip))

print("# generated by gen-members.py -- do not edit")
print("services:")
for name, ip in services:
    print(f"""  {name}:
    image: logos-sim:local
    hostname: {name}
    entrypoint: ["/opt/sim/member.sh"]
    environment:
      SEED_ADDR: /ip4/{seed}/tcp/44001/p2p/16Uiu2HAm4gVVMqAzg2gT5cBii3qfaXykUJoB7jyHgAu71RuiELmz
      LOOKUP_INTERVAL: ${{LOOKUP_INTERVAL:-15}}
      START_JITTER: ${{START_JITTER:-8}}
    depends_on:
      seed:
        condition: service_healthy
    volumes:
      - ./out/traces:/traces
    networks:
      sim:
        ipv4_address: {ip}""")

if targets_file:
    # Prometheus file_sd: the seed serves the delivery library's registry
    # directly; each member serves the merged document via its openmetrics
    # module. `node` is the label every dashboard selects on.
    with open(targets_file, "w") as f:
        json.dump(
            [{"targets": [f"{seed}:{SEED_METRICS_PORT}"],
              "labels": {"node": "seed", "role": "seed"}}]
            + [{"targets": [f"{ip}:{METRICS_PORT}"],
                "labels": {"node": name, "role": "member"}}
               for name, ip in services],
            f,
            indent=1,
        )
        f.write("\n")
